In [2]:
import numpy as np
import pandas as pd
import numpy.matlib as nm
import random

1. Create a NumPy array 'arr' of integers from 0 to 5 and print its data type.




In [2]:
arr= np.array([i for i in range(0,6)], dtype= int)
print("Datatype:",arr.dtype)
arr

Datatype: int32


array([0, 1, 2, 3, 4, 5])

2. Given a NumPy array 'arr', check if its data type is float64.

In [3]:
arr = np.array([1.5, 2.6, 3.7])
print(arr.dtype)

float64





3. Create a NumPy array 'arr' with a data type of complex128 containing three complex numbers.



In [4]:
arr=np.array([3+4j,4-8j,7+2j])
print(arr.dtype)
arr

complex128


array([3.+4.j, 4.-8.j, 7.+2.j])

4. Convert an existing NumPy array 'arr' of integers to float32 data type.

In [5]:
print("Array before conversion:")
arr=np.array([i for i in range(1,100,10)])
print("Datatype:", arr.dtype)
arr


Array before conversion:
Datatype: int32


array([ 1, 11, 21, 31, 41, 51, 61, 71, 81, 91])

In [6]:
print("Array after conversion:")
arr=np.array([i for i in range(1,100,10)],dtype=np.float32)
print("Datatype:", arr.dtype)
arr


Array after conversion:
Datatype: float32


array([ 1., 11., 21., 31., 41., 51., 61., 71., 81., 91.], dtype=float32)


5. Given a NumPy array 'arr' with float64 data type, convert it to float32 to reduce decimal precision.


In [7]:
arr1=np.random.rand(3)
print("Datatype:", arr1.dtype)
arr1


Datatype: float64


array([0.55961328, 0.32692439, 0.78418168])

In [8]:
arr1=arr1.astype(dtype=np.float32)
arr1



array([0.5596133 , 0.32692438, 0.78418165], dtype=float32)


6. Write a function array_attributes that takes a NumPy array as input and returns its shape, size, and data
type.

In [9]:
def array_attribute(arr):
    return arr.shape, arr.size, arr.dtype
arr=np.random.randint(2,10,(14,7))
shape, size,datatype= array_attribute(arr)
print(f"Shape of array: {shape}\nSize of array: {size}\nDatatype of array: {datatype}")

Shape of array: (14, 7)
Size of array: 98
Datatype of array: int32



7. Create a function array_dimension that takes a NumPy array as input and returns its dimensionality.


In [10]:
def array_dimension(arr):
    return arr.ndim
arr=np.random.randint(1,20,(3,6))
print(f"Dimension of array:{array_dimension(arr)}")


Dimension of array:2




8. Design a function item_size_info that takes a NumPy array as input and returns the item size and the total
size in bytes.


In [11]:
def item_size(arr):
    return arr.size,arr.nbytes
arr= np.random.rand(5,6)
print(f"Array:\n{arr}\nTotal size of array:{item_size(arr)[0]}\nTotal size in bytes:{item_size(arr)[1]}")

Array:
[[0.26815072 0.23843377 0.66537662 0.54103958 0.31037488 0.01680566]
 [0.20405656 0.11699722 0.6551349  0.45059784 0.26943743 0.95950039]
 [0.63990896 0.0427809  0.4830931  0.26960283 0.5472645  0.32096199]
 [0.25456068 0.93101152 0.32731197 0.88160402 0.47358797 0.34124703]
 [0.63850922 0.59589389 0.65891484 0.61107997 0.04247531 0.32402814]]
Total size of array:30
Total size in bytes:240


9. Create a function array_strides that takes a NumPy array as input and returns the strides of the array.

In [12]:
class Array_Strides():
    def array_strides(self, arr):
        return arr.strides
obj=Array_Strides()
arr=np.random.randint(4,80,(6,4))
obj.array_strides(arr)


(16, 4)

10. Design a function shape_stride_relationship that takes a NumPy array as input and returns the shape
and strides of the array.


In [13]:
class Shape_Stride_Relationship():
    def shape_stride_relationship(self, arr):
        return arr.shape , arr.strides
obj= Shape_Stride_Relationship()
arr=np.random.randint(4,50,(4,5))
print(f"Array:\n{arr}")
print(f"Shape of array{obj.shape_stride_relationship(arr)[0]}\nStrides of array:{obj.shape_stride_relationship(arr)[1]}")


Array:
[[27 12 45 41 31]
 [43 24 26 19 25]
 [27  6 33 44 36]
 [11 29 29 19 33]]
Shape of array(4, 5)
Strides of array:(20, 4)


11. Create a function `create_zeros_array` that takes an integer `n` as input and returns a NumPy array of
zeros with `n` elements.


In [14]:
class Crate_Zeros_Array():
    def create_zeros_array(self, n):
        return np.zeros(n,dtype=int)
obj=Crate_Zeros_Array()
n=int(input("Enter the value of n:"))
print(f"Value of n:{n}\nArray:")
obj.create_zeros_array(n)

Value of n:3
Array:


array([0, 0, 0])

12. Write a function `create_ones_matrix` that takes integers `rows` and `cols` as inputs and generates a 2D
NumPy array filled with ones of size `rows x cols`.


In [15]:
class Create_Ones_Matrix():
    def create_ones_matrix(self,rows, cols):
        return np.ones([rows,cols], dtype=int)
rows=int(input("Enter the rows:"))
cols=int(input("Enter the colums:"))
obj= Create_Ones_Matrix()
print(f"Rows:{rows}\nColums:{cols}")
obj.create_ones_matrix(rows,cols)

Rows:3
Colums:3


array([[1, 1, 1],
       [1, 1, 1],
       [1, 1, 1]])

13. Write a function `generate_range_array` that takes three integers start, stop, and step as arguments and
creates a NumPy array with a range starting from `start`, ending at stop (exclusive), and with the specified
`step`.


In [16]:
class Generate_range_array():
    def generate_range_array(self, start, end, step):
        return np.arange(start, end, step)
obj = Generate_range_array()
start=int(input("Enter start"))
stop=int(input("Enter stop"))
step=int(input("Enter step"))
print(f"Start:{start}\nStop:{stop}\nStep:{step}")
obj.generate_range_array(start, stop, step)


Start:3
Stop:3
Step:3


array([], dtype=int32)

14. Design a function `generate_linear_space` that takes two floats `start`, `stop`, and an integer `num` as
arguments and generates a NumPy array with num equally spaced values between `start` and `stop`
(inclusive).



In [17]:
class Generate_Linera_Space():
    def generate_linear_space(self, start, stop,num):
        return np.linspace(start,stop,num)
start=float(input("Enter Start"))
stop= float(input("Enter stop"))
num= int(input("Enter number"))
obj= Generate_Linera_Space()
print(f"Start:{start}\nStop:{stop}\nStep:{num}")
obj.generate_linear_space(start, stop, num)

Start:3.0
Stop:3.0
Step:3


array([3., 3., 3.])

15. Create a function `create_identity_matrix` that takes an integer `n` as input and generates a square
identity matrix of size `n x n` using `numpy.eye`.


In [18]:
def create_identity_matrix(n):
    return np.eye(n)
n=int(input("Enter number"))
print(f"Number:{n}")
create_identity_matrix(n)

Number:3


array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

16. Write a function that takes a Python list and converts it into a NumPy array.



In [19]:
def list_into_array(l):
    return np.asarray(l)
list_into_array([i for i in range(2,50,6)])

array([ 2,  8, 14, 20, 26, 32, 38, 44])


17. Create a NumPy array and demonstrate the use of `numpy.view` to create a new array object with the
same data.

In [20]:
arr=np.asarray([i for i in range(1,8)])
arr.dtype
arr.view(np.int16)

array([1, 0, 2, 0, 3, 0, 4, 0, 5, 0, 6, 0, 7, 0], dtype=int16)

18. Write a function that takes two NumPy arrays and concatenates them along a specified axis.

In [21]:
def concat_array(arr1,arr2):
    return np.concatenate([arr1,arr2],axis=0)
arr1=np.random.randint(1,50,(3,4))
arr2=np.random.randint(1,50,(3,4))
concat_array(arr1,arr2)

array([[25, 32, 11, 17],
       [ 7, 41, 26,  5],
       [ 5, 32, 21, 38],
       [22, 42, 33, 40],
       [25,  9, 38, 41],
       [ 5, 15, 37, 37]])

19. Create two NumPy arrays with different shapes and concatenate them horizontally using `numpy.concatenate`.

In [22]:
def horizonatal_concat(arr1,arr2):
    return np.concatenate([arr1,arr2],axis=1)
arr1=np.random.randint(1,20,(3,3))
arr2=np.random.randint(5,90,(3,3))
horizonatal_concat(arr1,arr2)

array([[ 9,  5,  6, 58, 43, 83],
       [ 1,  8,  6, 72,  8, 45],
       [17, 15,  9, 45,  5, 59]])

20. Write a function that vertically stacks multiple NumPy arrays given as a list.

In [23]:
def vertical_stacked_list(*args):
    arr=np.array([])
    for i in args:
        arr=np.concatenate([arr,np.array(i)],axis=0)
    return arr
list1=[1,2,3,4,5,]
list2=[6,7,8,9,0]
list3=[1,2,3,4,5,6,7]
list4=[8,9,0]
list5=[1,2,3,4]
print(f"list1:{list1}\nlist2:{list2}\nlist3:{list3}\nlist4:{list4}\nlist5:{list5}\nAfter Concatenation vertically:")
vertical_stacked_list(list1,list2,list3,list4,list5)


list1:[1, 2, 3, 4, 5]
list2:[6, 7, 8, 9, 0]
list3:[1, 2, 3, 4, 5, 6, 7]
list4:[8, 9, 0]
list5:[1, 2, 3, 4]
After Concatenation vertically:


array([1., 2., 3., 4., 5., 6., 7., 8., 9., 0., 1., 2., 3., 4., 5., 6., 7.,
       8., 9., 0., 1., 2., 3., 4.])

22. Write a Python function using NumPy to generate an array of 10 equally spaced values between 0 and 1
(inclusive).

In [24]:
def equally_spaced_array():
    return np.linspace(0,1,10)
equally_spaced_array()

array([0.        , 0.11111111, 0.22222222, 0.33333333, 0.44444444,
       0.55555556, 0.66666667, 0.77777778, 0.88888889, 1.        ])

23. Write a Python function using NumPy to create an array of 5 logarithmically spaced values between 1 and
1000 (inclusive).

In [25]:
def log_space_value():
    return np.logspace(1,1000,5,base=10)
log_space_value()

C:\Users\msi\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\numpy\core\function_base.py:298: RuntimeWarning: overflow encountered in power
  return _nx.power(base, y)


array([1.00000000e+001, 5.62341325e+250,             inf,             inf,
                   inf])

24. Create a Pandas DataFrame using a NumPy array that contains 5 rows and 3 columns, where the values
are random integers between 1 and 100.

In [26]:
pd.DataFrame(np.random.randint(1,100,(5,3)),columns=["col1", "col2", "col3"])

col1  col2  col3
0    82     6    76
1     5    15    20
2    96    88    77
3     1    24    74
4     2    71    73

25. Write a function that takes a Pandas DataFrame and replaces all negative values in a specific column
with zeros. Use NumPy operations within the Pandas DataFrame.

In [27]:
def neg_val_replace(df):
    df.col3=df[df>0].col3.fillna(0)
    return df

df=pd.DataFrame(np.random.randint(-50,50,(10,6)),columns=["col1","col2","col3","col4","col5","col6"])
print("DataFrame after removing negative number from specified column {col3}:")
neg_val_replace(df)



DataFrame after removing negative number from specified column {col3}:


col1  col2  col3  col4  col5  col6
0     6    44   0.0   -19    44    16
1   -35   -17   0.0    39    -8   -28
2   -16    23  22.0    31    -3    15
3   -42   -37   0.0   -45   -46    -5
4    36    43  31.0   -31    40    -5
5    35   -32   0.0    44    28    17
6   -12    -9  15.0   -34   -15    23
7   -20   -35   0.0   -11   -36     2
8   -42    22  28.0   -40    27    37
9    33   -21  19.0   -12    29   -32

26. Access the 3rd element from the given NumPy array.
    arr = np.array([10, 20, 30, 40, 50])

In [28]:
arr = np.array([10, 20, 30, 40, 50])
print(f"Third element: {arr[2]}")

Third element: 30


27. Retrieve the element at index (1, 2) from the 2D NumPy array.

    arr_2d = np.array([[1, 2, 3],
                   [4, 5, 6],
                   [7, 8, 9]])

In [29]:
arr_2d = np.array([[1, 2, 3],
                   [4, 5, 6],
                   [7, 8, 9]])
arr_2d[1:2]

array([[4, 5, 6]])

28. Using boolean indexing, extract elements greater than 5 from the given NumPy array.

    arr = np.array([3, 8, 2, 10, 5, 7])

In [30]:
arr = np.array([3, 8, 2, 10, 5, 7])
bool_index=arr>5
arr[bool_index]

array([ 8, 10,  7])

29. Perform basic slicing to extract elements from index 2 to 5 (inclusive) from the given NumPy array.
    
    arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [31]:
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9])
arr[2:6]

array([3, 4, 5, 6])

30. Slice the 2D NumPy array to extract the sub-array `[[2, 3], [5, 6]]` from the given array.

     aarr_2d = np.array([[1, 2, 3],
                         [4, 5, 6],
                         [7, 8, 9]])

In [32]:
aarr_2d = np.array([[1, 2, 3],
                    [4, 5, 6],
                    [7, 8, 9]])

arr_2d[0:2,1:3]

array([[2, 3],
       [5, 6]])

31. Write a NumPy function to extract elements in specific order from a given 2D array based on indices
provided in another array.

In [33]:
def extract_element(arr, index_arr):
    l=[]
    for i in index_arr:
       l.append(arr[i[0],i[1]]) 
    return l

arr=np.random.randint(1,100,(4,4))
np.printoptions(",")
index_arr=np.random.randint(0,4,(3,2))
print(f"Array:-\n{arr.tolist()}\nIndex array:-\n{index_arr}")
print(f"extracted element:-\n{extract_element(arr,index_arr)}")

Array:-
[[88, 50, 38, 95], [50, 42, 81, 11], [71, 55, 30, 29], [57, 23, 24, 92]]
Index array:-
[[0 1]
 [0 3]
 [3 1]]
extracted element:-
[50, 95, 23]


32. Create a NumPy function that filters elements greater than a threshold from a given 1D array using
boolean indexing.

In [34]:
def threshold_filter(arr,threshold):
    bool_index=arr>threshold
    return arr[bool_index]
arr=np.random.randint(1,200,20)
threshold=random.randint(1,200)
print(f"Array:-\n{arr.tolist()}\n\nThreshold:-{threshold}\n\nFilterd array:-")
threshold_filter(arr,threshold)

Array:-
[130, 77, 140, 179, 117, 146, 33, 14, 30, 39, 73, 172, 156, 92, 180, 196, 112, 103, 21, 54]

Threshold:-194

Filterd array:-


array([196])

33. Develop a NumPy function that extracts specific elements from a 3D array using indices provided in three
separate arrays for each dimension.

In [35]:
def extract_element_3d(arr,index_arr):
    l=[]
    for i in index_arr:
        l.append(arr[i[0],i[1],i[2]])
    return l
arr=np.random.randint(1,200,(2,3,4))
index_arr=np.random.randint(0,2,(4,3))
print(f"3D Array:-\n{repr(arr)}\n\nIndex_arr:-\n{repr(index_arr)}\n\nExtracted values:-")
extract_element_3d(arr,index_arr)


3D Array:-
array([[[120, 160,  44,  16],
        [108,   6,  92,  78],
        [ 99,  85, 132,  43]],

       [[102, 157, 105, 157],
        [179,  59, 119, 170],
        [  4, 102, 190,  48]]])

Index_arr:-
array([[0, 0, 1],
       [1, 0, 1],
       [0, 0, 1],
       [0, 0, 1]])

Extracted values:-


[160, 157, 160, 160]

34. Write a NumPy function that returns elements from an array where both two conditions are satisfied
using boolean indexing.

In [36]:
def bool_indexing_arr(arr, minn,maxx):
    bool_index=(arr>minn ) & (arr<maxx)
    arr=arr[bool_index]
    return arr

arr=np.random.randint(1,500,38)
maxx=random.randint(400,500)
minn=random.randint(1,200)
bool_index=(arr>minn ) & (arr<maxx)
print(repr(arr))
print(f"\nmin:{minn}\nmax:{maxx}")
print("\nValues bitween min value and max value:")
bool_indexing_arr(arr,minn,maxx)

array([289, 434,  40, 446, 252, 380, 255, 490,  13, 456, 238, 193, 220,
       441, 178, 218,   5, 446, 467, 351, 306, 429, 133, 370, 460, 405,
        35,  24, 298, 329,  57, 361,  13, 406, 362, 393, 224, 288])

min:199
max:430

Values bitween min value and max value:


array([289, 252, 380, 255, 238, 220, 218, 351, 306, 429, 370, 405, 298,
       329, 361, 406, 362, 393, 224, 288])

35. Create a NumPy function that extracts elements from a 2D array using row and column indices provided
in separate arrays.

In [37]:
def ele_from_2darray(arr,index_arr):
    l=[]
    for i in index_arr:
        l.append(arr[i[0],i[1]])
    return l
arr=np.random.rand(4,4)
index_arr=np.random.randint(0,3,(4,2))
print(f"{repr(arr)}\nIndex array:\n{repr(index_arr)}")
ele_from_2darray(arr,index_arr)


array([[0.05096147, 0.50808148, 0.50693369, 0.68922958],
       [0.71039359, 0.23577722, 0.63275073, 0.42466144],
       [0.1713482 , 0.44052029, 0.21736401, 0.559521  ],
       [0.12396713, 0.64420741, 0.73929696, 0.3162054 ]])
Index array:
array([[1, 0],
       [0, 0],
       [1, 1],
       [1, 0]])


[0.7103935918922396,
 0.05096146728423656,
 0.23577722489710473,
 0.7103935918922396]

36. Given an array arr of shape (3, 3), add a scalar value of 5 to each element using NumPy broadcasting.

In [38]:
arr=np.random.randint(1,200,(3,3))
arr1=arr+5
print(f"Origonal Array:\n{repr(arr)}\nAfter adding 5 in each element:\n{repr(arr1)}")

Origonal Array:
array([[121,  69,  74],
       [194, 188,  20],
       [ 34,  78, 177]])
After adding 5 in each element:
array([[126,  74,  79],
       [199, 193,  25],
       [ 39,  83, 182]])


37. Consider two arrays arr1 of shape (1, 3) and arr2 of shape (3, 4). Multiply each row of arr2 by the
corresponding element in arr1 using NumPy broadcasting.

In [39]:
arr1=np.random.randint(1,4,(1,3))
arr2=np.random.randint(2,6,(3,4))
l=[]
for i in range(len(arr2)):
    l.append(arr2[i]*arr1[0][i])
print(f"Array1:-\n{repr(arr1)}\nArray2:-\n{repr(arr2)}\nResultant array:-\n{repr(np.array(l))}")



Array1:-
array([[2, 3, 2]])
Array2:-
array([[4, 2, 4, 2],
       [2, 5, 3, 5],
       [2, 4, 5, 2]])
Resultant array:-
array([[ 8,  4,  8,  4],
       [ 6, 15,  9, 15],
       [ 4,  8, 10,  4]])


38. Given a 1D array arr1 of shape (1, 4) and a 2D array arr2 of shape (4, 3), add arr1 to each row of arr2 using
NumPy broadcasting.


In [40]:
arr1=np.random.randint(1,50,4)
arr2=np.random.randint(1,50,(4,3))
result=[]
for i in range(len(arr2)):
    result.append(arr2[i]+arr1[i])
print(f"Array1:-\n{repr(arr1)}\nArray2:-\n{repr(arr2)}\nResultant array:-\n{repr(np.array(result))}")

Array1:-
array([14, 42, 18, 31])
Array2:-
array([[ 9, 37, 17],
       [ 1, 46,  6],
       [ 4, 47,  9],
       [ 2, 23, 20]])
Resultant array:-
array([[23, 51, 31],
       [43, 88, 48],
       [22, 65, 27],
       [33, 54, 51]])


39. Consider two arrays arr1 of shape (3, 1) and arr2 of shape (1, 3). Add these arrays using NumPy
broadcasting.

In [41]:
arr1 = np.random.randint(1,50,(3,1))
arr2 = np.random.randint(1,20,(1,3))
print(f"Array 1 :\n{repr(arr1)}\n\nArray 2 :\n{repr(arr2)}\n\nUsing numpy broadcasting: \n{repr(arr1+arr2)}")

Array 1 :
array([[34],
       [31],
       [45]])

Array 2 :
array([[ 4, 11,  6]])

Using numpy broadcasting: 
array([[38, 45, 40],
       [35, 42, 37],
       [49, 56, 51]])


40. Given arrays arr1 of shape (2, 3) and arr2 of shape (2, 2), perform multiplication using NumPy
broadcasting. Handle the shape incompatibility.

In [4]:
arr1 = np.random.randint(1,50,(2,3))
arr2 = np.random.randint(1,20,(2,2))
print(f"Array 1 :\n{repr(arr1)}\n\nArray 2 :\n{repr(arr2)}")
arr1=np.reshape(arr1,(-1,1))
arr2= np.reshape(arr2,(1,-1))
print("\nAfter reshaping & numPy broadcasting:")
arr1*arr2



Array 1 :
array([[27, 32, 46],
       [44, 23,  5]])

Array 2 :
array([[ 1, 18],
       [18, 14]])

After reshaping & numPy broadcasting:


array([[ 27, 486, 486, 378],
       [ 32, 576, 576, 448],
       [ 46, 828, 828, 644],
       [ 44, 792, 792, 616],
       [ 23, 414, 414, 322],
       [  5,  90,  90,  70]])

41. Calculate column-wise mean for the given array:   
    arr = np.array([[1, 2, 3], [4, 5, 6]])

In [38]:
arr = np.array([[1, 2, 3], [4, 5, 6]])
arr=arr.T
list=[]
for i in arr:
    list.append(i.mean())
print(f"Array:\n{repr(arr.T)}\nColumn wise mean:\n{repr(np.asarray(list))}")

Array:
array([[1, 2, 3],
       [4, 5, 6]])
Column wise mean:
array([2.5, 3.5, 4.5])


42. Find maximum value in each row of the given array:   
    arr = np.array([[1, 2, 3], [4, 5, 6]])

In [39]:
arr = np.array([[1, 2, 3], [4, 5, 6]])
list=[]
for i in arr:
    list.append(np.max(i))
print(f"Array:\n{repr(arr)}\nMaximun value in each row:\n{repr(np.asarray(list))}")

Array:
array([[1, 2, 3],
       [4, 5, 6]])
Maximun value in each row:
array([3, 6])


43.  For the given array, find indices of maximum value in each column.   
      arr = np.array([[1, 2, 3], [4, 5, 6]])

43.  For the given array, find indices of maximum value in each column.   
      arr = np.array([[1, 2, 3], [4, 5, 6]])

44. For the given array, apply custom function to calculate moving sum along rows.   
    arr = np.array([[1, 2, 3], [4, 5, 6]])

45.  In the given array, check  if all elements in each column are even. 
        arr = np.array([[2, 4, 6], [3, 5, 7]])









46. Given a NumPy array arr, reshape it into a matrix of dimensions `m` rows and `n` columns. Return the 
reshaped matrix. 
    original_array = np.array([1, 2, 3, 4, 5, 6])


47. Create a function that takes a matrix as input and returns the flattened array.   
    input_matrix = np.array([[1, 2, 3], [4, 5, 6]])
    


48. Write a function that concatenates two given arrays along a specified axis. 



    array1 = np.array([[1, 2], [3, 4]]) 
    array2 = np.array([[5, 6], [7, 8]])

49. Create a function that splits an array into multiple sub-arrays along a specified axis. 
    original_array = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

50. Write a function that inserts and then deletes elements from a given array at specified indices. 
    original_array = np.array([1, 2, 3, 4, 5]) indices_to_insert = [2, 4] 
values_to_insert = [10, 11] 
indices_to_delete = [1, 3]
     
51. Create a NumPy array `arr1` with random integers and another array `arr2` with integers from 1 to 10. 
Perform element-wise addition between `arr1` and `arr2`.  

52. Generate a NumPy array `arr1` with sequential integers from 10 to 1 and another array `arr2` with integers 
from 1 to 10. Subtract `arr2` from `arr1` element-wise.  
53. Create a NumPy array `arr1` with random integers and another array `arr2` with integers from 1 to 5. 
Perform element-wise multiplication between `arr1` and `arr2`.  
54. Generate a NumPy array `arr1` with even integers from 2 to 10 and another array `arr2` with integers from 1 
to 5. Perform element-wise division of `arr1` by `arr2`.  
55. Create a NumPy array `arr1` with integers from 1 to 5 and another array `arr2` with the same numbers 
reversed. Calculate the exponentiation of `arr1` raised to the power of `arr2` element-wise.  
56. Write a function that counts the occurrences of a specific substring within a NumPy array of strings.
arr = np.array(['hello', 'world', 'hello', 'numpy', 'hello']) 
57. Write a function that extracts uppercase characters from a NumPy array of strings. 
arr = np.array(['Hello', 'World', 'OpenAI', 'GPT'])  


58. Write a function that replaces occurrences of a substring in a NumPy array of strings with a new string. 
arr = np.array(['apple', 'banana', 'grape', 'pineapple'])  
59. Write a function that concatenates strings in a NumPy array element-wise.    
arr1 = np.array(['Hello', 'World']) 
arr2 = np.array(['Open', 'AI'])

60. Write a function that finds the length of the longest string in a NumPy array. 
arr = np.array(['apple', 'banana', 'grape', 'pineapple'])   
61. Create a dataset of 100 random integers between 1 and 1000. Compute the mean, median, variance, and 
standard deviation of the dataset using NumPy's functions.  
62. Generate an array of 50 random numbers between 1 and 100. Find the 25th and 75th percentiles of the 
dataset.  
63. Create two arrays representing two sets of variables. Compute the correlation coefficient between these 
arrays using NumPy's `corrcoef` function.  
64. Create two matrices and perform matrix multiplication using NumPy's `dot` function.  
65. Create an array of 50 integers between 10 and 1000. Calculate the 10th, 50th (median), and 90th 
percentiles along with the first and third quartiles.  
66. Create a NumPy array of integers and find the index of a specific element.  
67. Generate a random NumPy array and sort it in ascending order.  
68. Filter elements >20  in the given NumPy array.

arr = np.array([12, 25, 6, 42, 8, 30])    
69. Filter elements which are divisible by 3 from a given NumPy array.   
arr = np.array([1, 5, 8, 12, 15])
70. Filter elements which are ≥ 20 and ≤ 40 from a given NumPy array.   
arr = np.array([10, 20, 30, 40, 50])
71. For the given NumPy array, check its byte order using the `dtype` attribute byteorder. 

arr = np.array([1, 2, 3])

72. For the given NumPy array, perform byte swapping in place using `byteswap()`.   
arr = np.array([1, 2, 3], dtype=np.int32)

73. For the given NumPy array, swap its byte order without modifying the original array using 
`newbyteorder()`.
arr = np.array([1, 2, 3], dtype=np.int32  ) 
74. For the given NumPy array and swap its byte order conditionally based on system endianness using 
`newbyteorder()`.   
arr = np.array([1, 2, 3], dtype=np.int32)
75. For the given NumPy array, check if byte swapping is necessary for the current system using `dtype` 
attribute `byteorder`.   
arr = np.array([1, 2, 3], dtype=np.int32)
76. Create a NumPy array `arr1` with values from 1 to 10. Create a copy of `arr1` named `copy_arr` and modify 
an element in `copy_arr`. Check if modifying `copy_arr` affects `arr1`.  
77. Create a 2D NumPy array `matrix` of shape (3, 3) with random integers. Extract a slice `view_slice` from 
the matrix. Modify an element in `view_slice` and observe if it changes the original `matrix`.  
78. Create a NumPy array `array_a` of shape (4, 3) with sequential integers from 1 to 12. Extract a slice 
`view_b` from `array_a` and broadcast the addition of 5 to view_b. Check if it alters the original `array_a`.  
79. Create a NumPy array `orig_array` of shape (2, 4) with values from 1 to 8. Create a reshaped view 
`reshaped_view` of shape (4, 2) from orig_array. Modify an element in `reshaped_view` and check if it 
reflects changes in the original `orig_array`.  
80. Create a NumPy array `data` of shape (3, 4) with random integers. Extract a copy `data_copy` of 
elements greater than 5. Modify an element in `data_copy` and verify if it affects the original `data`.  
81. Create two matrices A and B of identical shape containing integers and perform addition and subtraction 
operations between them.  
82. Generate two matrices `C` (3x2) and `D` (2x4) and perform matrix multiplication.  
83. Create a matrix `E` and find its transpose.  
84. Generate a square matrix `F` and compute its determinant.  
85. Create a square matrix `G` and find its inverse. 



In [ ]:
G=nm.matrix([])
G

matrix([], shape=(1, 0), dtype=float64)